server:
  port: 3355

spring:
  application:
    name: config-client
  cloud:
    config:
      label: main #分支名称
      name: config #配置文件名称
      profile: dev #配置文件后缀
      uri: http://localhost:3344
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
